
version: 2

models:
  - name: characters
  - name: professors
  #- name: int_customers_per_store
    #columns:
      #- name: store_id
        #tests:
          #- unique
          #- not_null
      #- name: total_customers
        #tests:
          #- not_null

  #- name: stg_payment
    #description: "Staging model consisting of payment events"
    #columns:
      #- name: payment_id
        #tests:
          #- unique
          #- not_null
      #- name: customer_id
        #tests:
          #- not_null
