
version: 2

models:
  - name: characters
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null

  - name: professors
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null
