dbt_spark_example:
  target: spark-hudi
  outputs:
    spark-hudi:
      type: spark
      method: thrift
      host: spark-hudi
      port: 10000
      schema: hudi_dbt
      threads: 1
    spark:
      type: spark
      method: thrift
      host: spark
      port: 10000
      schema: hudi_dbt
      threads: 1
