dbt_spark_example:
  target: spark-hudi
  outputs:
    postgres:
      type: postgres
      host: postgres
      database: dbt
      port: 5432
      user: dbt_role
      password: dbt_password
      schema: public
    spark-hudi:
      type: spark
      method: thrift
      host: spark-hudi
      port: 10000
      schema: hudi_dbt
      threads: 1
    spark:
      type: spark
      method: thrift
      host: spark
      port: 10000
      schema: hudi_dbt
      threads: 1
